[package]
name = "lapce"
version = "0.0.7"
authors = ["Dongdong Zhou <dzhou121@gmail.com>"]
edition = "2021"
resolver = "2"

[dependencies]
lapce-core = { path = "./core" }
lapce-proxy = { path = "./proxy" }

[[bin]]
name = "lapce"
path = "core/src/bin/lapce.rs"

[[bin]]
name = "lapce-proxy"
path = "proxy/src/bin/lapce-proxy.rs"

[workspace]
members = ["core", "proxy", "rpc"]

[profile.dev]
split-debuginfo = "unpacked"

[profile.release]
codegen-units = 1
lto = "thin"
# debug = true
