name: Release

on:
  workflow_dispatch:
  push:
    branches: [linux_build]
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get install cmake pkg-config libfreetype6-dev libfontconfig1-dev \
            libxcb-xfixes0-dev libxkbcommon-dev
      - run: wget -O- --quiet https://github.com/rui314/mold/releases/download/v${{ inputs.mold-version }}/mold-${{ inputs.mold-version }}-$(uname -m)-linux.tar.gz | sudo tar -C /usr/local --strip-components=1 -xzf -
        shell: bash
      - run: sudo ln -sf /usr/bin/mold $(realpath /usr/bin/ld); true
        shell: bash
      - name: Update rust
        run: rustup update
      - name: Build
        run: cargo build --release
      - name: Gzip 
        run: |
          mkdir Lapce
          cp ./target/release/lapce Lapce/
          tar -zcvf ./Lapce-linux.tar.gz Lapce
          gzip -c "./target/release/lapce-proxy" > ./lapce-proxy-linux.gz
      - name: Upload Application
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Lapce-linux.tar.gz
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
      - name: Upload Application
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./lapce-proxy-linux.gz
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true



