name: Release

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]
    branches:
      - scoop_build

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-2022

    strategy:
      matrix:
        include:
        - version: stable
          target: x86_64-pc-windows-msvc

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Update rust toolchain
        run: rustup update --no-self-update ${{ matrix.version }} && rustup default ${{ matrix.version }}
      - name: Build
        run: cargo build --release
      - name: Create msi installer
        run: |
          candle.exe -arch "x64" -ext WixUIExtension -ext WixUtilExtension \
            -out "./lapce.wixobj" "extra/windows/wix/lapce.wxs"
          light.exe -ext WixUIExtension -ext WixUtilExtension \
            -out "./Lapce-windows.msi" -sice:ICE61 -sice:ICE91 \
            "./lapce.wixobj"
      - name: Upload msi installer
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./Lapce-windows.msi
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
