name: Release

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: nightly
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+*"]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
      - name: Update rust
        run: rustup update
      - name: Build
        run: cargo build --profile release-lto
      - name: Install WiX
        run: nuget install WiX
      - name: Crate msi installer
        run: |
          ./WiX.*/tools/candle.exe -arch "x64" -ext WixUIExtension -ext WixUtilExtension \
            -out "./lapce.wixobj" "extra/windows/wix/lapce.wxs"
          ./WiX.*/tools/light.exe -ext WixUIExtension -ext WixUtilExtension \
            -out "./Lapce-windows.msi" -sice:ICE61 -sice:ICE91 \
            "./lapce.wixobj"
      - name: Create portable
        shell: pwsh
        run: |
          Compress-Archive ./target/release-lto/lapce.exe ./Lapce-windows-portable.zip
      - name: Create lapce-proxy archive
        shell: pwsh
        run: |
          $file = [System.IO.File]::Open((Join-Path $PWD '.\target\release-lto\lapce-proxy.exe'), [System.IO.FileMode]::Open)
          $archive = [System.IO.File]::Create((Join-Path $PWD '.\lapce-proxy-windows-x86_64.gz'))
          $compressor = [System.IO.Compression.GZipStream]::new($archive, [System.IO.Compression.CompressionMode]::Compress)
          $file.CopyTo($compressor)
          Start-Sleep -Seconds 10
          $compressor.close()
      - uses: actions/upload-artifact@v3
        with:
          name: lapce-windows
          path: |
            ./lapce-proxy-windows-*.gz
            ./Lapce-windows-portable.zip
            ./Lapce-windows.msi
          retention-days: 1

  linux:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cmake pkg-config libfontconfig-dev libgtk-3-dev
      - name: Update rust
        run: rustup update
      - name: Build
        run: cargo build --profile release-lto --bin lapce
      - name: Gzip
        run: |
          mkdir Lapce
          cp ./target/release-lto/lapce Lapce/
          tar -zcvf ./Lapce-linux.tar.gz Lapce
      - uses: actions/upload-artifact@v3
        with:
          name: lapce-linux
          path: |
            ./Lapce-linux.tar.gz
          retention-days: 1

  linux-musl:
    name: Build lapce-proxy for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
#         https://github.com/rust-lang/libc/pull/2788
#           - triple: i586-alpine-linux-musl
#             platform: x86
          - triple: x86_64-alpine-linux-musl
            platform: x86_64
#         currently broken on GitHub but not locally,
#         need to figure out why
#           - triple: aarch64-alpine-linux-musl
#             platform: aarch64
#         unsupported for now
#           - triple: armv6-alpine-linux-musleabihf
#             platform: armhf
#           - triple: armv7-alpine-linux-musleabihf
#             platform: armv7
#         unsupported for now
#           - triple: s390x-alpine-linux-musl
#             platform: s390x
#         unsupported for now
#           - triple: powerpc64le-alpine-linux-musl
#             platform: ppc64le
    steps:
      - uses: actions/checkout@v2

      - name: Set-up Alpine environment
        uses: jirutka/setup-alpine@v1
        with:
          branch: edge
          arch: ${{ matrix.platform }}
          extra-repositories: |
            http://dl-cdn.alpinelinux.org/alpine/edge/testing
          packages: >
            zlib-static freetype-static fontconfig-static
            libgit2-static libssh2-static openssl-libs-static
            libssl1.1 gtk+3.0-dev http-parser-dev cargo
            build-base openssl-dev git mold clang

      - name: Build ${{ matrix.triple }}
        shell: alpine.sh {0}
        env:
          LIBZ_SYS_STATIC: 1
          LIBSSH2_STATIC: 1
          LIBGIT2_STATIC: 1
          OPENSSL_STATIC: 1
          OPENSSL_NO_VENDOR: 1 # don't even try to build without it on musl
          PKG_CONFIG_ALL_STATIC: 1
          OPENSSL_DIR: /usr # static/dynamic lib workaround <3
          RUSTFLAGS: "-C target-feature=+crt-static" # link runtime static
          CARGO_BUILD_TARGET: ${{ matrix.triple }}
          CARGO_PROFILE_RELEASE_LTO: 'true'
          CARGO_PROFILE_RELEASE_STRIP: symbols # remove unneeded debug stuff
          CARGO_PROFILE_RELEASE_OPT_LEVEL: 's' # optimise for size
          CARGO_PROFILE_RELEASE_CODEGEN_UNITS: '1' # optimise each crate
          CARGO_NET_GIT_FETCH_WITH_CLI: 'true' # libgit2 workaround for some architectures
          CARGO_TARGET_x86_64-alpine-linux-musl_LINKER: clang
          CARGO_TARGET_x86_64-alpine-linux-musl_RUSTFLAGS: "-C link-arg=-fuse-ld=mold" # speed
          CARGO_TARGET_aarch64-alpine-linux-musl_LINKER: clang
          CARGO_TARGET_aarch64-alpine-linux-musl_RUSTFLAGS: "-C link-arg=-fuse-ld=mold" # speed
        run: |
          cargo build \
            --locked \
            --verbose \
            --release \
            --bin lapce-proxy \
            --manifest-path lapce-proxy/Cargo.toml
      - name: Gzip
        run: |
          gzip -c ./target/${{ matrix.triple }}/release/lapce-proxy > ./lapce-proxy-linux-${{ matrix.platform }}.gz
      - uses: actions/upload-artifact@v3
        with:
          name: lapce-proxy-linux-${{ matrix.platform }}
          path: |
            ./lapce-proxy-linux-*.gz
          retention-days: 1

  macos:
    runs-on: macos-11

    env:
      NOTARIZE_USERNAME: ${{ secrets.NOTARIZE_USERNAME }}
      NOTARIZE_PASSWORD: ${{ secrets.NOTARIZE_PASSWORD }}

    steps:
      - uses: actions/checkout@v2
      - name: Install ARM target
        run: rustup update && rustup target add aarch64-apple-darwin
      - name: Import Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.MACOS_CERTIFICATE }}
          p12-password: ${{ secrets.MACOS_CERTIFICATE_PWD }}
      - name: Make DMG
        run: make dmg-universal
      - name: Rename
        run: |
          cp ./target/release-lto/macos/Lapce.dmg ./target/release-lto/macos/Lapce-macos.dmg
      - name: Gzip lapce-proxy
        run: |
          gzip -c ./target/x86_64-apple-darwin/release-lto/lapce-proxy > ./lapce-proxy-darwin-x86_64.gz
          gzip -c ./target/aarch64-apple-darwin/release-lto/lapce-proxy > ./lapce-proxy-darwin-aarch64.gz
      - name: "Notarize Release Build"
        run: |
          npx notarize-cli --file ./target/release-lto/macos/Lapce-macos.dmg --bundle-id io.lapce --asc-provider CYSGAZFR8D
      - name: "Staple Release Build"
        uses: devbotsxyz/xcode-staple@v1
        with:
          product-path: "./target/release-lto/macos/Lapce-macos.dmg"
      - uses: actions/upload-artifact@v3
        with:
          name: lapce-macos
          path: |
            ./lapce-proxy-darwin-*.gz
            ./target/release-lto/macos/Lapce-macos.dmg
          retention-days: 1
          
  publish:
    needs: [linux, linux-musl, windows, macos]
    runs-on: ubuntu-20.04
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      # Must perform checkout first, since it deletes the target directory
      # before running, and would therefore delete the downloaded artifacts
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3          
      
      - if: github.event_name == 'workflow_dispatch'
        run: echo "TAG_NAME=${{ github.event.inputs.tag_name }}" >> $GITHUB_ENV
      - if: github.event_name == 'schedule'
        run: echo 'TAG_NAME=nightly' >> $GITHUB_ENV
      - if: github.event_name == 'push'
        run: |
          TAG_NAME=${{ github.ref }}
          echo "TAG_NAME=${TAG_NAME#refs/tags/}" >> $GITHUB_ENV
      - if: env.TAG_NAME == 'nightly'
        run: |
          (echo 'SUBJECT=Lapce development build';
           echo 'PRERELEASE=--prerelease') >> $GITHUB_ENV
          gh release delete nightly --yes || true
          git push origin :nightly || true
      - if: env.TAG_NAME != 'nightly'
        run: |
          (echo 'SUBJECT=Lapce release build';
           echo 'PRERELEASE=') >> $GITHUB_ENV
      - name: Publish release
        env:
          DEBUG: api
        run: |
          gh release create $TAG_NAME $PRERELEASE --title "$TAG_NAME" --target $GITHUB_SHA lapce-macos/* lapce-linux/* lapce-proxy-linux-*/* lapce-windows/*
